### ISSUE TITLE
crash to blank screen while viewing pair info

### ISSUE THREAD

**Issue by divine-comedian** [1Hive/honeyswap-info#22]
I'm viewing pair analytics for a particular pair and after 10-15 seconds the page crashes and my screen turns blank white - in the developer log there appears to be some typescript errors. - the URL is `https://info.honeyswap.org/#/pair/0xa69f95be0f36e8b3b143a509aee54fea46d8e189`

![image](https://user-images.githubusercontent.com/67759413/134456651-0b9cc9ae-d7c5-4860-9f54-b38efc31f5e4.png)

**Comment by kamikazebr** [comment]
https://info.honeyswap.org/#/pair/0x71641d6656ffb673f471ea292ea09ac528cc4df2

yeah i can reproduce it here also. Should be easy fix.

**Comment by kamikazebr** [comment]
@divine-comedian That is fixed now.
